In [2]:
import pandas as pd
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [9]:
def to_int(df):
    # strip all ',' from string numbers
    df = df.apply(lambda x: x.replace(',', '') if type(x) == str else x)
    return df.astype(float)

def get_codes(geo):
    geo = geo.split('US')[1]
    state = geo[:2]
    county = geo[2:5]
    tract = geo[5:len(geo) - 1]
    block = geo[-1]
    return state, county, tract, block

def get_county_name(geo_area_name):
    county_name = geo_area_name.split(',')[2].strip()
    return county_name
def get_state_name(geo_area_name):
    state_name = geo_area_name.split(',')[3].strip()
    return state_name

In [10]:
# read from first row
df = pd.read_csv('/Users/jack/Downloads/Decennial PL 2020 P1 Race/DECENNIALPL2020.P1-Data.csv', skiprows=1)
col_of_interest = ['Geography'] + list(df.columns[1:4]) + [col for col in df.columns[:-1] if '!!Total:!!Population of one race:!' in col] + [" !!Total:!!Population of two or more races:"]
df = df[col_of_interest]
rename_mapper = {
    " !!Total:": "Total Population",
    " !!Total:!!Population of one race:": "Total One Race",
    " !!Total:!!Population of one race:!!White alone": "White Only",
    " !!Total:!!Population of one race:!!Black or African American alone": "African American Only",
    " !!Total:!!Population of one race:!!American Indian and Alaska Native alone": "American Indian and Alaska Native Only",
    " !!Total:!!Population of one race:!!Asian alone": "Asain Only",
    " !!Total:!!Population of one race:!!Native Hawaiian and Other Pacific Islander alone": "Native Hawaiian and Other Pacific Islander Only",
    " !!Total:!!Population of one race:!!Some Other Race alone": "Others Only",
    " !!Total:!!Population of two or more races:": "Total Mixed Raced"
}
df = df.rename(columns=rename_mapper)

In [11]:
# get codes for the df
df['State'], df['County'], df['Tract'], df['Block'] = zip(*df['Geography'].map(get_codes))
df['County Name'] = df['Geographic Area Name'].map(get_county_name)
df['State Name'] = df['Geographic Area Name'].map(get_state_name)

In [12]:
df = df[
    [
        "State",
        "County",
        "Tract",
        "Block",
        "State Name",
        "County Name",
        "Total Population",
        "Total One Race",
        "White Only",
        "African American Only",
        "American Indian and Alaska Native Only",
        "Asain Only",
        "Native Hawaiian and Other Pacific Islander Only",
        "Others Only",
        "Total Mixed Raced",
    ]
]

# check for missing values
missing = df.isnull().sum()
# check for duplicates
duplicates = df.duplicated().sum()

In [78]:
df.to_csv("Race_block_group.csv", index=False)

## Race of Total Block Group

In [3]:
df = pd.read_csv("/Users/jack/Library/CloudStorage/GoogleDrive-limjackailjk@gmail.com/My Drive/Solar PV Lab/NIMBY Project/Solar NIMBY Final/Solar-NIMBY/data cleaning/Block Group/cleaned_data/Race_block_group.csv")
df.head()

,State,County,Tract,Block,State Name,County Name,Total Population,Total One Race,White Only,African American Only,American Indian and Alaska Native Only,Asain Only,Native Hawaiian and Other Pacific Islander Only,Others Only,Total Mixed Raced
0,1,1,20100,1,Alabama,Autauga County,575,523,433,73,0,5,0,12,52
1,1,1,20100,2,Alabama,Autauga County,1200,1130,956,140,5,3,3,23,70
2,1,1,20200,1,Alabama,Autauga County,974,942,311,615,2,7,0,7,32
3,1,1,20200,2,Alabama,Autauga County,1081,1042,531,489,0,5,4,13,39
4,1,1,20300,1,Alabama,Autauga County,2377,2243,1672,499,12,13,3,44,134

In [8]:
cols = df.columns[7:]
df[cols] = df[cols].div(df['Total Population'], axis=0)

In [10]:
# Rename all the columns to say percentage at the end
rename_mapper = {col: col + " Percentage" for col in cols}
df = df.rename(columns=rename_mapper)
df

,State,County,Tract,Block,State Name,County Name,Total Population,Total One Race Percentage,White Only Percentage,African American Only Percentage,American Indian and Alaska Native Only Percentage,Asian Only Percentage,Native Hawaiian and Other Pacific Islander Only Percentage,Others Only Percentage,Total Mixed Raced Percentage
0,1,1,20100,1,Alabama,Autauga County,575,0.909565,0.753043,0.126957,0.000000,0.008696,0.000000,0.020870,0.090435
1,1,1,20100,2,Alabama,Autauga County,1200,0.941667,0.796667,0.116667,0.004167,0.002500,0.002500,0.019167,0.058333
2,1,1,20200,1,Alabama,Autauga County,974,0.967146,0.319302,0.631417,0.002053,0.007187,0.000000,0.007187,0.032854
3,1,1,20200,2,Alabama,Autauga County,1081,0.963922,0.491212,0.452359,0.000000,0.004625,0.003700,0.012026,0.036078
4,1,1,20300,1,Alabama,Autauga County,2377,0.943626,0.703408,0.209928,0.005048,0.005469,0.001262,0.018511,0.056374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242328,72,153,750601,1,Puerto Rico,Yauco Municipio,1996,0.448898,0.138778,0.050601,0.006012,0.000501,0.000000,0.253006,0.551102
242329,72,153,750601,2,Puerto Rico,Yauco Municipio,963,0.549325,0.212876,0.025961,0.005192,0.000000,0.000000,0.305296,0.450675
242330,72,153,750601,3,Puerto Rico,Yauco Municipio,1409,0.564940,0.212917,0.055358,0.004258,0.000000,0.000000,0.292406,0.435060
242331,72,153,750602,1,Puerto Rico,Yauco Municipio,1359,0.590876,0.300957,0.044886,0.002943,0.000000,0.000000,0.242090,0.409124
242332,72,153,750602,2,Puerto Rico,Yauco Municipio,1228,0.472313,0.189739,0.035016,0.000000,0.000000,0.000000,0.247557,0.527687

In [11]:
df.to_csv("Race_Block_Group_Percentage.csv", index=False)

## Education level for the block group

In [5]:
df_edu = pd.read_csv("/Users/jack/Downloads/B15003 Educational Attainment 2022-10-31/ACSDT5Y2022.B15003-Data.csv", skiprows=1)

In [8]:
df_edu.columns

Index(['Geography', 'Geographic Area Name', 'Estimate!!Total:',
       'Margin of Error!!Total:', 'Estimate!!Total:!!No schooling completed',
       'Margin of Error!!Total:!!No schooling completed',
       'Estimate!!Total:!!Nursery school',
       'Margin of Error!!Total:!!Nursery school',
       'Estimate!!Total:!!Kindergarten',
       'Margin of Error!!Total:!!Kindergarten', 'Estimate!!Total:!!1st grade',
       'Margin of Error!!Total:!!1st grade', 'Estimate!!Total:!!2nd grade',
       'Margin of Error!!Total:!!2nd grade', 'Estimate!!Total:!!3rd grade',
       'Margin of Error!!Total:!!3rd grade', 'Estimate!!Total:!!4th grade',
       'Margin of Error!!Total:!!4th grade', 'Estimate!!Total:!!5th grade',
       'Margin of Error!!Total:!!5th grade', 'Estimate!!Total:!!6th grade',
       'Margin of Error!!Total:!!6th grade', 'Estimate!!Total:!!7th grade',
       'Margin of Error!!Total:!!7th grade', 'Estimate!!Total:!!8th grade',
       'Margin of Error!!Total:!!8th grade', 'Estimate!!Total:!!9th grade',
       'Margin of Error!!Total:!!9th grade', 'Estimate!!Total:!!10th grade',
       'Margin of Error!!Total:!!10th grade', 'Estimate!!Total:!!11th grade',
       'Margin of Error!!Total:!!11th grade',
       'Estimate!!Total:!!12th grade, no diploma',
       'Margin of Error!!Total:!!12th grade, no diploma',
       'Estimate!!Total:!!Regular high school diploma',
       'Margin of Error!!Total:!!Regular high school diploma',
       'Estimate!!Total:!!GED or alternative credential',
       'Margin of Error!!Total:!!GED or alternative credential',
       'Estimate!!Total:!!Some college, less than 1 year',
       'Margin of Error!!Total:!!Some college, less than 1 year',
       'Estimate!!Total:!!Some college, 1 or more years, no degree',
       'Margin of Error!!Total:!!Some college, 1 or more years, no degree',
       'Estimate!!Total:!!Associate's degree',
       'Margin of Error!!Total:!!Associate's degree',
       'Estimate!!Total:!!Bachelor's degree',
       'Margin of Error!!Total:!!Bachelor's degree',
       'Estimate!!Total:!!Master's degree',
       'Margin of Error!!Total:!!Master's degree',
       'Estimate!!Total:!!Professional school degree',
       'Margin of Error!!Total:!!Professional school degree',
       'Estimate!!Total:!!Doctorate degree',
       'Margin of Error!!Total:!!Doctorate degree', 'Unnamed: 52'],
      dtype='object')